on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

env:
  NODE_VERSION: "18.16.0"
  PNPM_VERSION: "8.6.3"
  PROXY_SUBDOMAIN: "dev"
  PROXY_ZONE_NAME: "wingcloud.io"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Projen
        run: pnpm run default

      - name: Compile Project
        run: pnpm run compile
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          BOT_GITHUB_CLIENT_ID: ${{ secrets.BOT_GITHUB_CLIENT_ID }}
          BOT_GITHUB_CLIENT_SECRET: ${{ secrets.BOT_GITHUB_CLIENT_SECRET }}
          BOT_GITHUB_APP_ID: ${{ secrets.BOT_GITHUB_APP_ID }}
          BOT_GITHUB_PRIVATE_KEY: ${{ secrets.BOT_GITHUB_PRIVATE_KEY }}
          BOT_GITHUB_WEBHOOK_SECRET: ${{ secrets.BOT_GITHUB_WEBHOOK_SECRET }}
          FLY_TOKEN: ${{ secrets.FLY_TOKEN }}
          FLY_ORG_SLUG: ${{ secrets.FLY_ORG_SLUG }}
          PROXY_SUBDOMAIN: ${{ env.PROXY_SUBDOMAIN }}
          PROXY_ZONE_NAME: ${{ env.PROXY_ZONE_NAME }}
