name: Deploy Production

on:
  push:
    branches:
      - production
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  diff:
    name: Deploy Production
    uses: ./.github/workflows/deploy.yml
    with:
      TF_BACKEND_STATE_FILE: "${{ github.repository }}/production/infrastructure/main.tfstate"
      AWS_REGION: "us-east-1"
      ENVIRONMENT_NAME: "production"
    secrets: inherit

