name: Deploy Staging

on:
  push:
    paths-ignore:
      - "**/*.md"
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  only_on_main:
    runs-on: ubuntu-20.04
    steps:
      - name: Fail if branch is not main
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
          exit 1
  deploy:
    needs: only_on_main
    name: Deploy Staging
    uses: ./.github/workflows/deploy.yml
    with:
      TF_BACKEND_STATE_FILE: "${{ github.repository }}/${{ github.base_ref }}/infrastructure/main.tfstate"
      AWS_REGION: "us-east-1"
      ENVIRONMENT_NAME: "staging"
    secrets: inherit

