name: Deploy Staging

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  AWS_REGION: "us-east-1"
  TF_BACKEND_BUCKET: ${{ vars.TF_BACKEND_BUCKET }}
  TF_BACKEND_BUCKET_REGION: ${{ vars.TF_BACKEND_BUCKET_REGION }}
  TF_BACKEND_LOCK_TABLE: ${{ vars.TF_BACKEND_LOCK_TABLE }}
  DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
  DNSIMPLE_ACCOUNT: ${{ secrets.DNSIMPLE_ACCOUNT }}
  APP_SECRET: ${{ secrets.APP_SECRET }}
  BOT_GITHUB_APP_ID: ${{ secrets.BOT_GITHUB_APP_ID }}
  BOT_GITHUB_CLIENT_ID: ${{ secrets.BOT_GITHUB_CLIENT_ID }}
  BOT_GITHUB_CLIENT_SECRET: ${{ secrets.BOT_GITHUB_CLIENT_SECRET }}
  BOT_GITHUB_PRIVATE_KEY: ${{ secrets.BOT_GITHUB_PRIVATE_KEY }}
  BOT_GITHUB_WEBHOOK_SECRET: ${{ secrets.BOT_GITHUB_WEBHOOK_SECRET }}
  FLY_ORG_SLUG: ${{ secrets.FLY_ORG_SLUG }}
  FLY_TOKEN: ${{ secrets.FLY_TOKEN }}
  PROXY_SUBDOMAIN: ${{ vars.PROXY_SUBDOMAIN }}
  PROXY_ZONE_NAME: ${{ vars.PROXY_ZONE_NAME }}
  VITE_GITHUB_APP_CLIENT_ID: ${{ secrets.VITE_GITHUB_APP_CLIENT_ID }}
  VITE_GITHUB_APP_NAME: ${{ secrets.VITE_GITHUB_APP_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://staging.winglang.io
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: gh-actions-wingcloud-staging
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Wing Cloud
        uses: winglang/wing-github-action/actions/deploy@main
        with:
          entry: 'main.w'
          target: 'tf-aws'
          working-directory: 'apps/@wingcloud/infrastructure'