name: Pull Request Diff

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches: [production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for commenting on PRs

jobs:
  diff:
    name: Diff Production
    uses: ./.github/workflows/diff.yml
    with:
      TF_BACKEND_STATE_FILE: "${{ github.repository }}/${{ github.base_ref }}/infrastructure/main.tfstate"
      AWS_REGION: "us-east-1"
      ENVIRONMENT_NAME: "production"
    secrets: inherit