name: Pull Request Diff

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for commenting on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke Test
        run: |
          curl -sSfL https://${{ $PROXY_SUBDOMAIN:+$PROXY_SUBDOMAIN. }}${{ vars.PROXY_ZONE_NAME }}/wrpc/health
        env:
          PROXY_SUBDOMAIN: ${{ vars.PROXY_SUBDOMAIN }}
  diff-staging:
    name: Diff Staging
    uses: ./.github/workflows/diff-shared.yml
    with:
      TF_BACKEND_STATE_FILE: "winglang/wing.cloud/main/infrastructure/main.tfstate"
      AWS_REGION: "us-east-1"
      ENVIRONMENT_NAME: "staging"
    secrets: inherit
  diff-production:
    name: Diff Production
    uses: ./.github/workflows/diff-shared.yml
    with:
      TF_BACKEND_STATE_FILE: "winglang/wing.cloud/production/infrastructure/main.tfstate"
      AWS_REGION: "us-east-1"
      ENVIRONMENT_NAME: "production"
    secrets: inherit
