name: Pull Request Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |-
            website
            runtime
            infra
            infrastructure
            repo
          types: |-
            feat
            fix
            docs
            chore
            rfc
            revert
            release
          subjectPattern: ^[^A-Z][^:]+[^.]$
          subjectPatternError: Subject must start with a lowercase, should not include ':' and should not end with a period
          requireScope: false
