name: Testing

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency:
  # we can't run unique across the repo, pending builds
  # will be cancelled when a new one is started which
  # is not what we want in this case. Can't be configured otherwise.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: write # This is required for commenting on PRs

env:
  AWS_REGION: "us-east-1"

jobs:
  aws:
    if: contains(github.event.pull_request.labels.*.name, 'test-aws')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Compile Wing Cloud dependencies
        run: npx turbo compile --filter=!@wingcloud/infrastructure
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: gh-actions-wingcloud-testing
          aws-region: ${{ env.AWS_REGION }}
      - name: Run Wing Tests
        env:
          ## Inflight
          APP_SECRET: ${{ secrets.APP_SECRET }}
          FLY_ORG_SLUG: ${{ secrets.FLY_ORG_SLUG }}
          FLY_TOKEN: ${{ secrets.FLY_TOKEN }}
          BOT_GITHUB_APP_ID: ${{ secrets.BOT_GITHUB_APP_ID }}
          BOT_GITHUB_CLIENT_ID: ${{ secrets.BOT_GITHUB_CLIENT_ID }}
          BOT_GITHUB_CLIENT_SECRET: ${{ secrets.BOT_GITHUB_CLIENT_SECRET }}
          BOT_GITHUB_PRIVATE_KEY: ${{ secrets.BOT_GITHUB_PRIVATE_KEY }}
          BOT_GITHUB_WEBHOOK_SECRET: ${{ secrets.BOT_GITHUB_WEBHOOK_SECRET }}

          ## Inflight Testing
          TESTS_GITHUB_TOKEN: ${{ secrets.TESTS_GITHUB_TOKEN }}
          TESTS_GITHUB_USER: ${{ vars.TESTS_GITHUB_USER }}

          ## Preflight
          VITE_GITHUB_APP_CLIENT_ID: ${{ secrets.VITE_GITHUB_APP_CLIENT_ID }}
          VITE_GITHUB_APP_NAME: ${{ secrets.VITE_GITHUB_APP_NAME }}
          PROXY_SUBDOMAIN: ${{ vars.PROXY_SUBDOMAIN }}
          PROXY_ZONE_NAME: ${{ vars.PROXY_ZONE_NAME }}
          TF_BACKEND_BUCKET: ${{ vars.TF_BACKEND_BUCKET }}
          TF_BACKEND_BUCKET_REGION: ${{ vars.TF_BACKEND_BUCKET_REGION }}
          TF_BACKEND_LOCK_TABLE: ${{ vars.TF_BACKEND_LOCK_TABLE }}
          TF_BACKEND_STATE_FILE: "${{ github.repository }}/${{ github.base_ref }}/infrastructure/main.tfstate"
          LANDING_DOMAIN: ${{ vars.LANDING_DOMAIN }}
          TF_IN_AUTOMATION: true
          ENVIRONMENT_SERVER_ZONE_NAME:  ${{ vars.ENVIRONMENT_SERVER_ZONE_NAME }}
          ENVIRONMENT_SERVER_CERTIFICATE_ID:  ${{ vars.ENVIRONMENT_SERVER_CERTIFICATE_ID }}

          # dnsimple provider
          DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
          DNSIMPLE_ACCOUNT: ${{ secrets.DNSIMPLE_ACCOUNT }}

          # for `flyctl auth docker` in terraform
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

          TF_LOG: info
          TF_LOG_PATH: ${{ runner.workspace }}/terraform.log

          # Wing Platfrom
          WING_ENV: "test"
          # Wing debug logging
          DEBUG: "wing:*"
        run: pnpm wing test -t @wingcloud/platform main.w
        working-directory: 'apps/@wingcloud/infrastructure'
      - name: Output Terraform log
        if: failure()
        run: cat ${{ runner.workspace }}/terraform.log